### Data Cleaning using numpy

**The following are the student marks of a class**
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]



1. Find the no of outliers and missing values?
2. replace the outliers with 45 and missing value with 87.
3. what is the average marks of students after 2nd step?
4. How many students got less than 60 marks?
5. what is the maximum marks?
6. Convert the marks to float32.

### Solving Linear Equations


    
1. 2x + 3y - z = 10

    x - y + 2z = 5
    
    3x + 2y + z = 12
    
    
    
2. 2x + y - z + 3w = 8

    3x - 2y + 2z + 2w = 1
    
    x + 3y - 2z + w = 7
    
    4x - y + z - 2w = 3
   
   
   
3. 4x + 2y - 3z = 10

    -2x + 3y + z = -3
    
    x - y + 2z = 4
    
Solve the system of equations using NumPy's linalg.solve function.


### Conditional Selection with np.where()


1.	Generate a random 1D array A of 10 integers between 1 and 100.

2.	Use np.where() to find the indices where the elements of A are greater than 50.

3.	Create a new array B that contains elements from A where the condition is met.

4.	Calculate the mean of array B and print it along with arrays A and B.

### Replace Values with np.where()

1.	Create a 4x4 random integer matrix C with values between -10 and 10.

2.	Use np.where() to replace all negative values in matrix C with 0.

3.	Print the original matrix C and the modified matrix.

In [1]:
import numpy as np

In [5]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])

In [6]:
np.isnan(marks)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False])

In [9]:
a = (marks[(marks > 100) | (marks < 0)])
a                                               # outliers

array([188., 120., 122.])

In [10]:
len(a) 

3

In [11]:
np.sum(np.isnan(marks))                    # no of missing values

4

In [13]:
marks1 = np.where(np.isnan(marks),87,marks).astype("float32")
marks1

array([ 44.,  24.,  87.,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  87.,  87.,   3.,  56.,  81.,  59., 122.,  92.,  87.,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.], dtype=float32)

In [14]:
np.mean(marks1)

67.13793

In [15]:
marks2 = np.where((marks1 > 100) | (marks1 < 0),45,marks1)
marks2

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.], dtype=float32)

In [16]:
np.mean(marks2)

56.96552

In [17]:
max(marks2)

97.0

In [18]:
len(marks[marks2 < 60])

18

In [19]:
np.sum(marks2 < 60)

18

### Solving Linear Equations

1.2x + 3y - z = 10

x - y + 2z = 5

3x + 2y + z = 12

In [20]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])

In [21]:
b = np.array([10,5,12])

In [22]:
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

2. 2x + y - z + 3w = 8

3x - 2y + 2z + 2w = 1

x + 3y - 2z + w = 7

4x - y + z - 2w = 3

In [23]:
c = np.matrix([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-1]])

In [24]:
d = np.array([8,1,7,3])

In [25]:
np.linalg.solve(c,d)

array([ 1.58823529, -0.55882353, -3.17647059,  0.73529412])

3. 4x + 2y - 3z = 10

-2x + 3y + z = -3

x - y + 2z = 4

In [26]:
x = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])

In [27]:
y = np.array([10,-3,4])

In [28]:
np.linalg.solve(x,y)

array([2.85365854, 0.6097561 , 0.87804878])

### Conditional Selection with np.where()

1.Generate a random 1D array A of 10 integers between 1 and 100.

2.Use np.where() to find the indices where the elements of A are greater than 50.

3.Create a new array B that contains elements from A where the condition is met.

4.Calculate the mean of array B and print it along with arrays A and B.

In [29]:
a = np.arange(1,100)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
b = np.where((a>50))
b

(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98],
       dtype=int64),)

In [31]:
np.mean(b)

74.0

### Replace Values with np.where()

1.Create a 4x4 random integer matrix C with values between -10 and 10.

2.Use np.where() to replace all negative values in matrix C with 0.

3.Print the original matrix C and the modified matrix.

In [32]:
n = np.random.randint(-10,10,16).reshape(4,4)

In [33]:
n1 = np.where(n<0,0,n)

In [34]:
n

array([[ -2,  -9,   8,   2],
       [ -9,  -9,  -6,   7],
       [  0,  -7,   5,  -1],
       [ -3,  -9, -10,  -2]])

In [35]:
n1

array([[0, 0, 8, 2],
       [0, 0, 0, 7],
       [0, 0, 5, 0],
       [0, 0, 0, 0]])